name: Push Dir
author: Casper da Costa-Luis
description: Cleanly push directory contents to a branch
inputs:
  message:
    description: Commit message
    required: true
  branch:
    description: Branch to push to
    required: true
  name:
    description: Git committer name
    default: github-actions[bot]
    required: false
  email:
    description: Git committer email
    default: 41898282+github-actions[bot]@users.noreply.github.com
    required: false
  dir:
    description: Directory to push
    default: .
    required: false
  force:
    description: Set to "true" to force push
    required: false
  history:
    description: |
      Set to "false" to discard any prior commits on the `branch`
      (Note: "false" will override `force` to "true")
    default: true
    required: false
  cname:
    description: Text to inject into a `CNAME` file
    default: ""
    required: false
  nojekyll:
    description: Set to "true" to add a `.nojekyll` file
    required: false
branding:
  icon: upload-cloud
  color: black
runs:
  using: composite
  steps:
    - name: Push Branch
      run: bash push.sh
      shell: bash
      env:
        INPUT_DIR: ${{ inputs.dir }}
        INPUT_NAME: ${{ inputs.name }}
        INPUT_EMAIL: ${{ inputs.email }}
        INPUT_HISTORY: ${{ inputs.history }}
        INPUT_BRANCH: ${{ inputs.branch }}
        INPUT_CNAME: ${{ inputs.cname }}
        INPUT_NOJEKYLL: ${{ inputs.nojekyll }}
        INPUT_MESSAGE: ${{ inputs.message }}
        INPUT_FORCE: ${{ inputs.force }}
